//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package com.ibm.wssvt.acme.annuity.business.impl.ws.jaxws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement(name = "findContactByIdResponse", namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/pojoimpl/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "findContactByIdResponse", namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/pojoimpl/")
public class FindContactByIdResponse {

    @XmlElement(name = "return", namespace = "")
    private com.ibm.wssvt.acme.annuity.common.bean.jaxbjpa.Contact _return;

    /**
     * 
     * @return
     *     returns Contact
     */
    public com.ibm.wssvt.acme.annuity.common.bean.jaxbjpa.Contact getReturn() {
        return this._return;
    }

    /**
     * 
     * @param _return
     *     the value for the _return property
     */
    public void setReturn(com.ibm.wssvt.acme.annuity.common.bean.jaxbjpa.Contact _return) {
        this._return = _return;
    }

}
