//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl;

import java.util.List;
import java.util.concurrent.Future;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;

import com.ibm.wssvt.acme.annuity.common.bean.jaxbjpa.AnnuityHolder;
import com.ibm.wssvt.acme.annuity.common.bean.jaxbjpa.AnnuityValueObject;
import com.ibm.wssvt.acme.annuity.common.bean.jaxbjpa.Contact;
import com.ibm.wssvt.acme.annuity.common.bean.jaxbjpa.Payor;
import com.ibm.wssvt.acme.annuity.common.bean.jaxbjpa.PayoutValueObject;
import com.ibm.wssvt.acme.annuity.common.bean.jaxbjpa.Rider;

@WebService(name = "AnnuityMgmtSvcEJB30JAXWS", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/")
@XmlSeeAlso({
    com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.ObjectFactory.class,
    com.ibm.wssvt.acme.annuity.common.bean.jaxbjpa.ObjectFactory.class
})
public interface AnnuityMgmtSvcEJB30JAXWS {


    /**
     * 
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.CreateAnnuityResponse>
     */
    @WebMethod(operationName = "createAnnuity")
    @RequestWrapper(localName = "createAnnuity", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.CreateAnnuity")
    @ResponseWrapper(localName = "createAnnuityResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.CreateAnnuityResponse")
    public Response<CreateAnnuityResponse> createAnnuityAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        AnnuityValueObject arg0);

    /**
     * 
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "createAnnuity")
    @RequestWrapper(localName = "createAnnuity", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.CreateAnnuity")
    @ResponseWrapper(localName = "createAnnuityResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.CreateAnnuityResponse")
    public Future<?> createAnnuityAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        AnnuityValueObject arg0,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<CreateAnnuityResponse> asyncHandler);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.ibm.wssvt.acme.annuity.common.bean.jaxbjpa.AnnuityValueObject
     * @throws ServerPersistenceModuleException_Exception
     * @throws ServerBusinessModuleException_Exception
     * @throws EntityAlreadyExistsException_Exception
     * @throws InvalidArgumentException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createAnnuity", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.CreateAnnuity")
    @ResponseWrapper(localName = "createAnnuityResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.CreateAnnuityResponse")
    public AnnuityValueObject createAnnuity(
        @WebParam(name = "arg0", targetNamespace = "")
        AnnuityValueObject arg0)
        throws EntityAlreadyExistsException_Exception, InvalidArgumentException_Exception, ServerBusinessModuleException_Exception, ServerPersistenceModuleException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.UpdateAnnuityResponse>
     */
    @WebMethod(operationName = "updateAnnuity")
    @RequestWrapper(localName = "updateAnnuity", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.UpdateAnnuity")
    @ResponseWrapper(localName = "updateAnnuityResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.UpdateAnnuityResponse")
    public Response<UpdateAnnuityResponse> updateAnnuityAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        AnnuityValueObject arg0);

    /**
     * 
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "updateAnnuity")
    @RequestWrapper(localName = "updateAnnuity", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.UpdateAnnuity")
    @ResponseWrapper(localName = "updateAnnuityResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.UpdateAnnuityResponse")
    public Future<?> updateAnnuityAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        AnnuityValueObject arg0,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<UpdateAnnuityResponse> asyncHandler);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.ibm.wssvt.acme.annuity.common.bean.jaxbjpa.AnnuityValueObject
     * @throws ServerPersistenceModuleException_Exception
     * @throws ServerBusinessModuleException_Exception
     * @throws InvalidArgumentException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateAnnuity", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.UpdateAnnuity")
    @ResponseWrapper(localName = "updateAnnuityResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.UpdateAnnuityResponse")
    public AnnuityValueObject updateAnnuity(
        @WebParam(name = "arg0", targetNamespace = "")
        AnnuityValueObject arg0)
        throws InvalidArgumentException_Exception, ServerBusinessModuleException_Exception, ServerPersistenceModuleException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.DeleteAnnuityResponse>
     */
    @WebMethod(operationName = "deleteAnnuity")
    @RequestWrapper(localName = "deleteAnnuity", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.DeleteAnnuity")
    @ResponseWrapper(localName = "deleteAnnuityResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.DeleteAnnuityResponse")
    public Response<DeleteAnnuityResponse> deleteAnnuityAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        AnnuityValueObject arg0);

    /**
     * 
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "deleteAnnuity")
    @RequestWrapper(localName = "deleteAnnuity", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.DeleteAnnuity")
    @ResponseWrapper(localName = "deleteAnnuityResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.DeleteAnnuityResponse")
    public Future<?> deleteAnnuityAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        AnnuityValueObject arg0,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<DeleteAnnuityResponse> asyncHandler);

    /**
     * 
     * @param arg0
     * @throws ServerPersistenceModuleException_Exception
     * @throws ServerBusinessModuleException_Exception
     * @throws InvalidArgumentException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteAnnuity", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.DeleteAnnuity")
    @ResponseWrapper(localName = "deleteAnnuityResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.DeleteAnnuityResponse")
    public void deleteAnnuity(
        @WebParam(name = "arg0", targetNamespace = "")
        AnnuityValueObject arg0)
        throws InvalidArgumentException_Exception, ServerBusinessModuleException_Exception, ServerPersistenceModuleException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.CreateAnnuityHolderResponse>
     */
    @WebMethod(operationName = "createAnnuityHolder")
    @RequestWrapper(localName = "createAnnuityHolder", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.CreateAnnuityHolder")
    @ResponseWrapper(localName = "createAnnuityHolderResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.CreateAnnuityHolderResponse")
    public Response<CreateAnnuityHolderResponse> createAnnuityHolderAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        AnnuityHolder arg0);

    /**
     * 
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "createAnnuityHolder")
    @RequestWrapper(localName = "createAnnuityHolder", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.CreateAnnuityHolder")
    @ResponseWrapper(localName = "createAnnuityHolderResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.CreateAnnuityHolderResponse")
    public Future<?> createAnnuityHolderAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        AnnuityHolder arg0,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<CreateAnnuityHolderResponse> asyncHandler);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.ibm.wssvt.acme.annuity.common.bean.jaxbjpa.AnnuityHolder
     * @throws ServerPersistenceModuleException_Exception
     * @throws ServerBusinessModuleException_Exception
     * @throws EntityAlreadyExistsException_Exception
     * @throws InvalidArgumentException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createAnnuityHolder", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.CreateAnnuityHolder")
    @ResponseWrapper(localName = "createAnnuityHolderResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.CreateAnnuityHolderResponse")
    public AnnuityHolder createAnnuityHolder(
        @WebParam(name = "arg0", targetNamespace = "")
        AnnuityHolder arg0)
        throws EntityAlreadyExistsException_Exception, InvalidArgumentException_Exception, ServerBusinessModuleException_Exception, ServerPersistenceModuleException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.UpdateAnnuityHolderResponse>
     */
    @WebMethod(operationName = "updateAnnuityHolder")
    @RequestWrapper(localName = "updateAnnuityHolder", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.UpdateAnnuityHolder")
    @ResponseWrapper(localName = "updateAnnuityHolderResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.UpdateAnnuityHolderResponse")
    public Response<UpdateAnnuityHolderResponse> updateAnnuityHolderAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        AnnuityHolder arg0);

    /**
     * 
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "updateAnnuityHolder")
    @RequestWrapper(localName = "updateAnnuityHolder", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.UpdateAnnuityHolder")
    @ResponseWrapper(localName = "updateAnnuityHolderResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.UpdateAnnuityHolderResponse")
    public Future<?> updateAnnuityHolderAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        AnnuityHolder arg0,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<UpdateAnnuityHolderResponse> asyncHandler);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.ibm.wssvt.acme.annuity.common.bean.jaxbjpa.AnnuityHolder
     * @throws ServerPersistenceModuleException_Exception
     * @throws ServerBusinessModuleException_Exception
     * @throws InvalidArgumentException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateAnnuityHolder", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.UpdateAnnuityHolder")
    @ResponseWrapper(localName = "updateAnnuityHolderResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.UpdateAnnuityHolderResponse")
    public AnnuityHolder updateAnnuityHolder(
        @WebParam(name = "arg0", targetNamespace = "")
        AnnuityHolder arg0)
        throws InvalidArgumentException_Exception, ServerBusinessModuleException_Exception, ServerPersistenceModuleException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.DeleteAnnuityHolderResponse>
     */
    @WebMethod(operationName = "deleteAnnuityHolder")
    @RequestWrapper(localName = "deleteAnnuityHolder", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.DeleteAnnuityHolder")
    @ResponseWrapper(localName = "deleteAnnuityHolderResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.DeleteAnnuityHolderResponse")
    public Response<DeleteAnnuityHolderResponse> deleteAnnuityHolderAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        AnnuityHolder arg0);

    /**
     * 
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "deleteAnnuityHolder")
    @RequestWrapper(localName = "deleteAnnuityHolder", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.DeleteAnnuityHolder")
    @ResponseWrapper(localName = "deleteAnnuityHolderResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.DeleteAnnuityHolderResponse")
    public Future<?> deleteAnnuityHolderAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        AnnuityHolder arg0,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<DeleteAnnuityHolderResponse> asyncHandler);

    /**
     * 
     * @param arg0
     * @throws ServerPersistenceModuleException_Exception
     * @throws ServerBusinessModuleException_Exception
     * @throws InvalidArgumentException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteAnnuityHolder", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.DeleteAnnuityHolder")
    @ResponseWrapper(localName = "deleteAnnuityHolderResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.DeleteAnnuityHolderResponse")
    public void deleteAnnuityHolder(
        @WebParam(name = "arg0", targetNamespace = "")
        AnnuityHolder arg0)
        throws InvalidArgumentException_Exception, ServerBusinessModuleException_Exception, ServerPersistenceModuleException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.CreatePayorResponse>
     */
    @WebMethod(operationName = "createPayor")
    @RequestWrapper(localName = "createPayor", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.CreatePayor")
    @ResponseWrapper(localName = "createPayorResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.CreatePayorResponse")
    public Response<CreatePayorResponse> createPayorAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        Payor arg0);

    /**
     * 
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "createPayor")
    @RequestWrapper(localName = "createPayor", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.CreatePayor")
    @ResponseWrapper(localName = "createPayorResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.CreatePayorResponse")
    public Future<?> createPayorAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        Payor arg0,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<CreatePayorResponse> asyncHandler);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.ibm.wssvt.acme.annuity.common.bean.jaxbjpa.Payor
     * @throws ServerPersistenceModuleException_Exception
     * @throws EntityAlreadyExistsException_Exception
     * @throws ServerBusinessModuleException_Exception
     * @throws InvalidArgumentException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createPayor", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.CreatePayor")
    @ResponseWrapper(localName = "createPayorResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.CreatePayorResponse")
    public Payor createPayor(
        @WebParam(name = "arg0", targetNamespace = "")
        Payor arg0)
        throws EntityAlreadyExistsException_Exception, InvalidArgumentException_Exception, ServerBusinessModuleException_Exception, ServerPersistenceModuleException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.UpdatePayorResponse>
     */
    @WebMethod(operationName = "updatePayor")
    @RequestWrapper(localName = "updatePayor", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.UpdatePayor")
    @ResponseWrapper(localName = "updatePayorResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.UpdatePayorResponse")
    public Response<UpdatePayorResponse> updatePayorAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        Payor arg0);

    /**
     * 
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "updatePayor")
    @RequestWrapper(localName = "updatePayor", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.UpdatePayor")
    @ResponseWrapper(localName = "updatePayorResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.UpdatePayorResponse")
    public Future<?> updatePayorAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        Payor arg0,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<UpdatePayorResponse> asyncHandler);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.ibm.wssvt.acme.annuity.common.bean.jaxbjpa.Payor
     * @throws ServerPersistenceModuleException_Exception
     * @throws ServerBusinessModuleException_Exception
     * @throws InvalidArgumentException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updatePayor", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.UpdatePayor")
    @ResponseWrapper(localName = "updatePayorResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.UpdatePayorResponse")
    public Payor updatePayor(
        @WebParam(name = "arg0", targetNamespace = "")
        Payor arg0)
        throws InvalidArgumentException_Exception, ServerBusinessModuleException_Exception, ServerPersistenceModuleException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.DeletePayorResponse>
     */
    @WebMethod(operationName = "deletePayor")
    @RequestWrapper(localName = "deletePayor", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.DeletePayor")
    @ResponseWrapper(localName = "deletePayorResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.DeletePayorResponse")
    public Response<DeletePayorResponse> deletePayorAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        Payor arg0);

    /**
     * 
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "deletePayor")
    @RequestWrapper(localName = "deletePayor", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.DeletePayor")
    @ResponseWrapper(localName = "deletePayorResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.DeletePayorResponse")
    public Future<?> deletePayorAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        Payor arg0,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<DeletePayorResponse> asyncHandler);

    /**
     * 
     * @param arg0
     * @throws ServerPersistenceModuleException_Exception
     * @throws ServerBusinessModuleException_Exception
     * @throws InvalidArgumentException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deletePayor", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.DeletePayor")
    @ResponseWrapper(localName = "deletePayorResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.DeletePayorResponse")
    public void deletePayor(
        @WebParam(name = "arg0", targetNamespace = "")
        Payor arg0)
        throws InvalidArgumentException_Exception, ServerBusinessModuleException_Exception, ServerPersistenceModuleException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.CreateContactResponse>
     */
    @WebMethod(operationName = "createContact")
    @RequestWrapper(localName = "createContact", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.CreateContact")
    @ResponseWrapper(localName = "createContactResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.CreateContactResponse")
    public Response<CreateContactResponse> createContactAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        Contact arg0);

    /**
     * 
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "createContact")
    @RequestWrapper(localName = "createContact", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.CreateContact")
    @ResponseWrapper(localName = "createContactResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.CreateContactResponse")
    public Future<?> createContactAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        Contact arg0,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<CreateContactResponse> asyncHandler);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.ibm.wssvt.acme.annuity.common.bean.jaxbjpa.Contact
     * @throws ServerPersistenceModuleException_Exception
     * @throws ServerBusinessModuleException_Exception
     * @throws EntityAlreadyExistsException_Exception
     * @throws InvalidArgumentException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createContact", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.CreateContact")
    @ResponseWrapper(localName = "createContactResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.CreateContactResponse")
    public Contact createContact(
        @WebParam(name = "arg0", targetNamespace = "")
        Contact arg0)
        throws EntityAlreadyExistsException_Exception, InvalidArgumentException_Exception, ServerBusinessModuleException_Exception, ServerPersistenceModuleException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.UpdateContactResponse>
     */
    @WebMethod(operationName = "updateContact")
    @RequestWrapper(localName = "updateContact", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.UpdateContact")
    @ResponseWrapper(localName = "updateContactResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.UpdateContactResponse")
    public Response<UpdateContactResponse> updateContactAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        Contact arg0);

    /**
     * 
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "updateContact")
    @RequestWrapper(localName = "updateContact", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.UpdateContact")
    @ResponseWrapper(localName = "updateContactResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.UpdateContactResponse")
    public Future<?> updateContactAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        Contact arg0,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<UpdateContactResponse> asyncHandler);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.ibm.wssvt.acme.annuity.common.bean.jaxbjpa.Contact
     * @throws ServerPersistenceModuleException_Exception
     * @throws ServerBusinessModuleException_Exception
     * @throws InvalidArgumentException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateContact", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.UpdateContact")
    @ResponseWrapper(localName = "updateContactResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.UpdateContactResponse")
    public Contact updateContact(
        @WebParam(name = "arg0", targetNamespace = "")
        Contact arg0)
        throws InvalidArgumentException_Exception, ServerBusinessModuleException_Exception, ServerPersistenceModuleException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.DeleteContactResponse>
     */
    @WebMethod(operationName = "deleteContact")
    @RequestWrapper(localName = "deleteContact", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.DeleteContact")
    @ResponseWrapper(localName = "deleteContactResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.DeleteContactResponse")
    public Response<DeleteContactResponse> deleteContactAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        Contact arg0);

    /**
     * 
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "deleteContact")
    @RequestWrapper(localName = "deleteContact", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.DeleteContact")
    @ResponseWrapper(localName = "deleteContactResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.DeleteContactResponse")
    public Future<?> deleteContactAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        Contact arg0,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<DeleteContactResponse> asyncHandler);

    /**
     * 
     * @param arg0
     * @throws ServerPersistenceModuleException_Exception
     * @throws ServerBusinessModuleException_Exception
     * @throws InvalidArgumentException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteContact", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.DeleteContact")
    @ResponseWrapper(localName = "deleteContactResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.DeleteContactResponse")
    public void deleteContact(
        @WebParam(name = "arg0", targetNamespace = "")
        Contact arg0)
        throws InvalidArgumentException_Exception, ServerBusinessModuleException_Exception, ServerPersistenceModuleException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.CreatePayoutResponse>
     */
    @WebMethod(operationName = "createPayout")
    @RequestWrapper(localName = "createPayout", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.CreatePayout")
    @ResponseWrapper(localName = "createPayoutResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.CreatePayoutResponse")
    public Response<CreatePayoutResponse> createPayoutAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        PayoutValueObject arg0);

    /**
     * 
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "createPayout")
    @RequestWrapper(localName = "createPayout", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.CreatePayout")
    @ResponseWrapper(localName = "createPayoutResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.CreatePayoutResponse")
    public Future<?> createPayoutAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        PayoutValueObject arg0,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<CreatePayoutResponse> asyncHandler);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.ibm.wssvt.acme.annuity.common.bean.jaxbjpa.PayoutValueObject
     * @throws ServerPersistenceModuleException_Exception
     * @throws ServerBusinessModuleException_Exception
     * @throws EntityAlreadyExistsException_Exception
     * @throws InvalidArgumentException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createPayout", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.CreatePayout")
    @ResponseWrapper(localName = "createPayoutResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.CreatePayoutResponse")
    public PayoutValueObject createPayout(
        @WebParam(name = "arg0", targetNamespace = "")
        PayoutValueObject arg0)
        throws EntityAlreadyExistsException_Exception, InvalidArgumentException_Exception, ServerBusinessModuleException_Exception, ServerPersistenceModuleException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.UpdatePayoutResponse>
     */
    @WebMethod(operationName = "updatePayout")
    @RequestWrapper(localName = "updatePayout", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.UpdatePayout")
    @ResponseWrapper(localName = "updatePayoutResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.UpdatePayoutResponse")
    public Response<UpdatePayoutResponse> updatePayoutAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        PayoutValueObject arg0);

    /**
     * 
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "updatePayout")
    @RequestWrapper(localName = "updatePayout", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.UpdatePayout")
    @ResponseWrapper(localName = "updatePayoutResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.UpdatePayoutResponse")
    public Future<?> updatePayoutAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        PayoutValueObject arg0,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<UpdatePayoutResponse> asyncHandler);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.ibm.wssvt.acme.annuity.common.bean.jaxbjpa.PayoutValueObject
     * @throws ServerPersistenceModuleException_Exception
     * @throws ServerBusinessModuleException_Exception
     * @throws InvalidArgumentException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updatePayout", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.UpdatePayout")
    @ResponseWrapper(localName = "updatePayoutResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.UpdatePayoutResponse")
    public PayoutValueObject updatePayout(
        @WebParam(name = "arg0", targetNamespace = "")
        PayoutValueObject arg0)
        throws InvalidArgumentException_Exception, ServerBusinessModuleException_Exception, ServerPersistenceModuleException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.DeletePayoutResponse>
     */
    @WebMethod(operationName = "deletePayout")
    @RequestWrapper(localName = "deletePayout", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.DeletePayout")
    @ResponseWrapper(localName = "deletePayoutResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.DeletePayoutResponse")
    public Response<DeletePayoutResponse> deletePayoutAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        PayoutValueObject arg0);

    /**
     * 
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "deletePayout")
    @RequestWrapper(localName = "deletePayout", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.DeletePayout")
    @ResponseWrapper(localName = "deletePayoutResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.DeletePayoutResponse")
    public Future<?> deletePayoutAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        PayoutValueObject arg0,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<DeletePayoutResponse> asyncHandler);

    /**
     * 
     * @param arg0
     * @throws ServerPersistenceModuleException_Exception
     * @throws ServerBusinessModuleException_Exception
     * @throws InvalidArgumentException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deletePayout", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.DeletePayout")
    @ResponseWrapper(localName = "deletePayoutResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.DeletePayoutResponse")
    public void deletePayout(
        @WebParam(name = "arg0", targetNamespace = "")
        PayoutValueObject arg0)
        throws InvalidArgumentException_Exception, ServerBusinessModuleException_Exception, ServerPersistenceModuleException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.DeleteRiderResponse>
     */
    @WebMethod(operationName = "deleteRider")
    @RequestWrapper(localName = "deleteRider", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.DeleteRider")
    @ResponseWrapper(localName = "deleteRiderResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.DeleteRiderResponse")
    public Response<DeleteRiderResponse> deleteRiderAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        Rider arg0);

    /**
     * 
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "deleteRider")
    @RequestWrapper(localName = "deleteRider", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.DeleteRider")
    @ResponseWrapper(localName = "deleteRiderResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.DeleteRiderResponse")
    public Future<?> deleteRiderAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        Rider arg0,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<DeleteRiderResponse> asyncHandler);

    /**
     * 
     * @param arg0
     * @throws ServerPersistenceModuleException_Exception
     * @throws ServerBusinessModuleException_Exception
     * @throws InvalidArgumentException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteRider", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.DeleteRider")
    @ResponseWrapper(localName = "deleteRiderResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.DeleteRiderResponse")
    public void deleteRider(
        @WebParam(name = "arg0", targetNamespace = "")
        Rider arg0)
        throws InvalidArgumentException_Exception, ServerBusinessModuleException_Exception, ServerPersistenceModuleException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.FindAnnuityByIdResponse>
     */
    @WebMethod(operationName = "findAnnuityById")
    @RequestWrapper(localName = "findAnnuityById", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.FindAnnuityById")
    @ResponseWrapper(localName = "findAnnuityByIdResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.FindAnnuityByIdResponse")
    public Response<FindAnnuityByIdResponse> findAnnuityByIdAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        AnnuityValueObject arg0);

    /**
     * 
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "findAnnuityById")
    @RequestWrapper(localName = "findAnnuityById", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.FindAnnuityById")
    @ResponseWrapper(localName = "findAnnuityByIdResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.FindAnnuityByIdResponse")
    public Future<?> findAnnuityByIdAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        AnnuityValueObject arg0,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<FindAnnuityByIdResponse> asyncHandler);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.ibm.wssvt.acme.annuity.common.bean.jaxbjpa.AnnuityValueObject
     * @throws ServerPersistenceModuleException_Exception
     * @throws ServerBusinessModuleException_Exception
     * @throws EntityNotFoundException_Exception
     * @throws InvalidArgumentException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAnnuityById", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.FindAnnuityById")
    @ResponseWrapper(localName = "findAnnuityByIdResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.FindAnnuityByIdResponse")
    public AnnuityValueObject findAnnuityById(
        @WebParam(name = "arg0", targetNamespace = "")
        AnnuityValueObject arg0)
        throws EntityNotFoundException_Exception, InvalidArgumentException_Exception, ServerBusinessModuleException_Exception, ServerPersistenceModuleException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.FindHolderByIdResponse>
     */
    @WebMethod(operationName = "findHolderById")
    @RequestWrapper(localName = "findHolderById", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.FindHolderById")
    @ResponseWrapper(localName = "findHolderByIdResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.FindHolderByIdResponse")
    public Response<FindHolderByIdResponse> findHolderByIdAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        AnnuityHolder arg0);

    /**
     * 
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "findHolderById")
    @RequestWrapper(localName = "findHolderById", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.FindHolderById")
    @ResponseWrapper(localName = "findHolderByIdResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.FindHolderByIdResponse")
    public Future<?> findHolderByIdAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        AnnuityHolder arg0,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<FindHolderByIdResponse> asyncHandler);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.ibm.wssvt.acme.annuity.common.bean.jaxbjpa.AnnuityHolder
     * @throws ServerPersistenceModuleException_Exception
     * @throws ServerBusinessModuleException_Exception
     * @throws EntityNotFoundException_Exception
     * @throws InvalidArgumentException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findHolderById", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.FindHolderById")
    @ResponseWrapper(localName = "findHolderByIdResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.FindHolderByIdResponse")
    public AnnuityHolder findHolderById(
        @WebParam(name = "arg0", targetNamespace = "")
        AnnuityHolder arg0)
        throws EntityNotFoundException_Exception, InvalidArgumentException_Exception, ServerBusinessModuleException_Exception, ServerPersistenceModuleException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.FindContactByIdResponse>
     */
    @WebMethod(operationName = "findContactById")
    @RequestWrapper(localName = "findContactById", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.FindContactById")
    @ResponseWrapper(localName = "findContactByIdResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.FindContactByIdResponse")
    public Response<FindContactByIdResponse> findContactByIdAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        Contact arg0);

    /**
     * 
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "findContactById")
    @RequestWrapper(localName = "findContactById", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.FindContactById")
    @ResponseWrapper(localName = "findContactByIdResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.FindContactByIdResponse")
    public Future<?> findContactByIdAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        Contact arg0,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<FindContactByIdResponse> asyncHandler);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.ibm.wssvt.acme.annuity.common.bean.jaxbjpa.Contact
     * @throws ServerPersistenceModuleException_Exception
     * @throws ServerBusinessModuleException_Exception
     * @throws EntityNotFoundException_Exception
     * @throws InvalidArgumentException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findContactById", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.FindContactById")
    @ResponseWrapper(localName = "findContactByIdResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.FindContactByIdResponse")
    public Contact findContactById(
        @WebParam(name = "arg0", targetNamespace = "")
        Contact arg0)
        throws EntityNotFoundException_Exception, InvalidArgumentException_Exception, ServerBusinessModuleException_Exception, ServerPersistenceModuleException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.FindHolderAnnuitiesResponse>
     */
    @WebMethod(operationName = "findHolderAnnuities")
    @RequestWrapper(localName = "findHolderAnnuities", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.FindHolderAnnuities")
    @ResponseWrapper(localName = "findHolderAnnuitiesResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.FindHolderAnnuitiesResponse")
    public Response<FindHolderAnnuitiesResponse> findHolderAnnuitiesAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        AnnuityHolder arg0);

    /**
     * 
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "findHolderAnnuities")
    @RequestWrapper(localName = "findHolderAnnuities", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.FindHolderAnnuities")
    @ResponseWrapper(localName = "findHolderAnnuitiesResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.FindHolderAnnuitiesResponse")
    public Future<?> findHolderAnnuitiesAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        AnnuityHolder arg0,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<FindHolderAnnuitiesResponse> asyncHandler);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.ibm.wssvt.acme.annuity.common.bean.jaxbjpa.AnnuityValueObject>
     * @throws ServerPersistenceModuleException_Exception
     * @throws ServerBusinessModuleException_Exception
     * @throws InvalidArgumentException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findHolderAnnuities", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.FindHolderAnnuities")
    @ResponseWrapper(localName = "findHolderAnnuitiesResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.FindHolderAnnuitiesResponse")
    public List<AnnuityValueObject> findHolderAnnuities(
        @WebParam(name = "arg0", targetNamespace = "")
        AnnuityHolder arg0)
        throws InvalidArgumentException_Exception, ServerBusinessModuleException_Exception, ServerPersistenceModuleException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.FindAnnuityHolderResponse>
     */
    @WebMethod(operationName = "findAnnuityHolder")
    @RequestWrapper(localName = "findAnnuityHolder", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.FindAnnuityHolder")
    @ResponseWrapper(localName = "findAnnuityHolderResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.FindAnnuityHolderResponse")
    public Response<FindAnnuityHolderResponse> findAnnuityHolderAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        AnnuityValueObject arg0);

    /**
     * 
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "findAnnuityHolder")
    @RequestWrapper(localName = "findAnnuityHolder", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.FindAnnuityHolder")
    @ResponseWrapper(localName = "findAnnuityHolderResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.FindAnnuityHolderResponse")
    public Future<?> findAnnuityHolderAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        AnnuityValueObject arg0,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<FindAnnuityHolderResponse> asyncHandler);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.ibm.wssvt.acme.annuity.common.bean.jaxbjpa.AnnuityHolder
     * @throws ServerPersistenceModuleException_Exception
     * @throws ServerBusinessModuleException_Exception
     * @throws EntityNotFoundException_Exception
     * @throws InvalidArgumentException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAnnuityHolder", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.FindAnnuityHolder")
    @ResponseWrapper(localName = "findAnnuityHolderResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.FindAnnuityHolderResponse")
    public AnnuityHolder findAnnuityHolder(
        @WebParam(name = "arg0", targetNamespace = "")
        AnnuityValueObject arg0)
        throws EntityNotFoundException_Exception, InvalidArgumentException_Exception, ServerBusinessModuleException_Exception, ServerPersistenceModuleException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.FindPayorAnnuitiesResponse>
     */
    @WebMethod(operationName = "findPayorAnnuities")
    @RequestWrapper(localName = "findPayorAnnuities", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.FindPayorAnnuities")
    @ResponseWrapper(localName = "findPayorAnnuitiesResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.FindPayorAnnuitiesResponse")
    public Response<FindPayorAnnuitiesResponse> findPayorAnnuitiesAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        Payor arg0);

    /**
     * 
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "findPayorAnnuities")
    @RequestWrapper(localName = "findPayorAnnuities", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.FindPayorAnnuities")
    @ResponseWrapper(localName = "findPayorAnnuitiesResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.FindPayorAnnuitiesResponse")
    public Future<?> findPayorAnnuitiesAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        Payor arg0,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<FindPayorAnnuitiesResponse> asyncHandler);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.ibm.wssvt.acme.annuity.common.bean.jaxbjpa.AnnuityValueObject>
     * @throws ServerPersistenceModuleException_Exception
     * @throws ServerBusinessModuleException_Exception
     * @throws InvalidArgumentException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findPayorAnnuities", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.FindPayorAnnuities")
    @ResponseWrapper(localName = "findPayorAnnuitiesResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.FindPayorAnnuitiesResponse")
    public List<AnnuityValueObject> findPayorAnnuities(
        @WebParam(name = "arg0", targetNamespace = "")
        Payor arg0)
        throws InvalidArgumentException_Exception, ServerBusinessModuleException_Exception, ServerPersistenceModuleException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.FindPayorByIdResponse>
     */
    @WebMethod(operationName = "findPayorById")
    @RequestWrapper(localName = "findPayorById", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.FindPayorById")
    @ResponseWrapper(localName = "findPayorByIdResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.FindPayorByIdResponse")
    public Response<FindPayorByIdResponse> findPayorByIdAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        Payor arg0);

    /**
     * 
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "findPayorById")
    @RequestWrapper(localName = "findPayorById", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.FindPayorById")
    @ResponseWrapper(localName = "findPayorByIdResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.FindPayorByIdResponse")
    public Future<?> findPayorByIdAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        Payor arg0,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<FindPayorByIdResponse> asyncHandler);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.ibm.wssvt.acme.annuity.common.bean.jaxbjpa.Payor
     * @throws ServerPersistenceModuleException_Exception
     * @throws ServerBusinessModuleException_Exception
     * @throws EntityNotFoundException_Exception
     * @throws InvalidArgumentException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findPayorById", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.FindPayorById")
    @ResponseWrapper(localName = "findPayorByIdResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.FindPayorByIdResponse")
    public Payor findPayorById(
        @WebParam(name = "arg0", targetNamespace = "")
        Payor arg0)
        throws EntityNotFoundException_Exception, InvalidArgumentException_Exception, ServerBusinessModuleException_Exception, ServerPersistenceModuleException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.FindPayoutByIdResponse>
     */
    @WebMethod(operationName = "findPayoutById")
    @RequestWrapper(localName = "findPayoutById", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.FindPayoutById")
    @ResponseWrapper(localName = "findPayoutByIdResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.FindPayoutByIdResponse")
    public Response<FindPayoutByIdResponse> findPayoutByIdAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        PayoutValueObject arg0);

    /**
     * 
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "findPayoutById")
    @RequestWrapper(localName = "findPayoutById", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.FindPayoutById")
    @ResponseWrapper(localName = "findPayoutByIdResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.FindPayoutByIdResponse")
    public Future<?> findPayoutByIdAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        PayoutValueObject arg0,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<FindPayoutByIdResponse> asyncHandler);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.ibm.wssvt.acme.annuity.common.bean.jaxbjpa.PayoutValueObject
     * @throws ServerPersistenceModuleException_Exception
     * @throws ServerBusinessModuleException_Exception
     * @throws EntityNotFoundException_Exception
     * @throws InvalidArgumentException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findPayoutById", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.FindPayoutById")
    @ResponseWrapper(localName = "findPayoutByIdResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.FindPayoutByIdResponse")
    public PayoutValueObject findPayoutById(
        @WebParam(name = "arg0", targetNamespace = "")
        PayoutValueObject arg0)
        throws EntityNotFoundException_Exception, InvalidArgumentException_Exception, ServerBusinessModuleException_Exception, ServerPersistenceModuleException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.FindRiderByIdResponse>
     */
    @WebMethod(operationName = "findRiderById")
    @RequestWrapper(localName = "findRiderById", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.FindRiderById")
    @ResponseWrapper(localName = "findRiderByIdResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.FindRiderByIdResponse")
    public Response<FindRiderByIdResponse> findRiderByIdAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        Rider arg0);

    /**
     * 
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "findRiderById")
    @RequestWrapper(localName = "findRiderById", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.FindRiderById")
    @ResponseWrapper(localName = "findRiderByIdResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.FindRiderByIdResponse")
    public Future<?> findRiderByIdAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        Rider arg0,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<FindRiderByIdResponse> asyncHandler);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.ibm.wssvt.acme.annuity.common.bean.jaxbjpa.Rider
     * @throws ServerPersistenceModuleException_Exception
     * @throws ServerBusinessModuleException_Exception
     * @throws EntityNotFoundException_Exception
     * @throws InvalidArgumentException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findRiderById", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.FindRiderById")
    @ResponseWrapper(localName = "findRiderByIdResponse", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", className = "com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.FindRiderByIdResponse")
    public Rider findRiderById(
        @WebParam(name = "arg0", targetNamespace = "")
        Rider arg0)
        throws EntityNotFoundException_Exception, InvalidArgumentException_Exception, ServerBusinessModuleException_Exception, ServerPersistenceModuleException_Exception
    ;

}
