//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for annuityHolderCategory.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="annuityHolderCategory">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="METAL"/>
 *     &lt;enumeration value="BRONZE"/>
 *     &lt;enumeration value="SILVER"/>
 *     &lt;enumeration value="GOLD"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "annuityHolderCategory", namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/")
@XmlEnum
public enum AnnuityHolderCategory {

    METAL,
    BRONZE,
    SILVER,
    GOLD;

    public String value() {
        return name();
    }

    public static AnnuityHolderCategory fromValue(String v) {
        return valueOf(v);
    }

}
