//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "AnnuityMgmtSvcEJB30JAXWSImpl", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", wsdlLocation = "http://localhost:9081/AcmeAnnuityEJB3JAXWS/AnnuityMgmtSvcEJB30JAXWSImpl/META-INF/wsdl/AnnuityMgmtSvcEJB30JAXWSImpl.wsdl")
public class AnnuityMgmtSvcEJB30JAXWSImpl
    extends Service
{

    private final static URL ANNUITYMGMTSVCEJB30JAXWSIMPL_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:9081/AcmeAnnuityEJB3JAXWS/AnnuityMgmtSvcEJB30JAXWSImpl/META-INF/wsdl/AnnuityMgmtSvcEJB30JAXWSImpl.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        ANNUITYMGMTSVCEJB30JAXWSIMPL_WSDL_LOCATION = url;
    }

    public AnnuityMgmtSvcEJB30JAXWSImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AnnuityMgmtSvcEJB30JAXWSImpl() {
        super(ANNUITYMGMTSVCEJB30JAXWSIMPL_WSDL_LOCATION, new QName("http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", "AnnuityMgmtSvcEJB30JAXWSImpl"));
    }

    /**
     * 
     * @return
     *     returns AnnuityMgmtSvcEJB30JAXWS
     */
    @WebEndpoint(name = "AnnuityMgmtSvcEJB3JAXWSImplPort")
    public AnnuityMgmtSvcEJB30JAXWS getAnnuityMgmtSvcEJB3JAXWSImplPort() {
        return (AnnuityMgmtSvcEJB30JAXWS)super.getPort(new QName("http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", "AnnuityMgmtSvcEJB3JAXWSImplPort"), AnnuityMgmtSvcEJB30JAXWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AnnuityMgmtSvcEJB30JAXWS
     */
    @WebEndpoint(name = "AnnuityMgmtSvcEJB3JAXWSImplPort")
    public AnnuityMgmtSvcEJB30JAXWS getAnnuityMgmtSvcEJB3JAXWSImplPort(WebServiceFeature... features) {
        return (AnnuityMgmtSvcEJB30JAXWS)super.getPort(new QName("http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", "AnnuityMgmtSvcEJB3JAXWSImplPort"), AnnuityMgmtSvcEJB30JAXWS.class, features);
    }

}
