//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

import com.ibm.wssvt.acme.annuity.common.bean.jaxbjpa.PayoutValueObject;


/**
 * <p>Java class for deletePayout complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="deletePayout">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="arg0" type="{http://bean.common.annuity.acme.wssvt.ibm.com/jaxbjpa/}PayoutValueObject" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "deletePayout", namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", propOrder = {
    "arg0"
})
public class DeletePayout {

    protected PayoutValueObject arg0;

    /**
     * Gets the value of the arg0 property.
     * 
     * @return
     *     possible object is
     *     {@link PayoutValueObject }
     *     
     */
    public PayoutValueObject getArg0() {
        return arg0;
    }

    /**
     * Sets the value of the arg0 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PayoutValueObject }
     *     
     */
    public void setArg0(PayoutValueObject value) {
        this.arg0 = value;
    }

}
