//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DeleteAnnuityHolder_QNAME = new QName("http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", "deleteAnnuityHolder");
    private final static QName _CreateAnnuity_QNAME = new QName("http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", "createAnnuity");
    private final static QName _UpdateAnnuityHolderResponse_QNAME = new QName("http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", "updateAnnuityHolderResponse");
    private final static QName _EntityNotFoundException_QNAME = new QName("http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", "EntityNotFoundException");
    private final static QName _FindHolderAnnuities_QNAME = new QName("http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", "findHolderAnnuities");
    private final static QName _UpdateAnnuityResponse_QNAME = new QName("http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", "updateAnnuityResponse");
    private final static QName _CreatePayorResponse_QNAME = new QName("http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", "createPayorResponse");
    private final static QName _DeleteContactResponse_QNAME = new QName("http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", "deleteContactResponse");
    private final static QName _FindAnnuityByIdResponse_QNAME = new QName("http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", "findAnnuityByIdResponse");
    private final static QName _UpdatePayout_QNAME = new QName("http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", "updatePayout");
    private final static QName _DeleteAnnuity_QNAME = new QName("http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", "deleteAnnuity");
    private final static QName _UpdatePayor_QNAME = new QName("http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", "updatePayor");
    private final static QName _CreatePayout_QNAME = new QName("http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", "createPayout");
    private final static QName _FindPayorAnnuitiesResponse_QNAME = new QName("http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", "findPayorAnnuitiesResponse");
    private final static QName _FindPayorById_QNAME = new QName("http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", "findPayorById");
    private final static QName _InvalidArgumentException_QNAME = new QName("http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", "InvalidArgumentException");
    private final static QName _FindContactByIdResponse_QNAME = new QName("http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", "findContactByIdResponse");
    private final static QName _UpdateContactResponse_QNAME = new QName("http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", "updateContactResponse");
    private final static QName _UpdateAnnuityHolder_QNAME = new QName("http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", "updateAnnuityHolder");
    private final static QName _FindAnnuityById_QNAME = new QName("http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", "findAnnuityById");
    private final static QName _UpdateAnnuity_QNAME = new QName("http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", "updateAnnuity");
    private final static QName _DeleteRiderResponse_QNAME = new QName("http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", "deleteRiderResponse");
    private final static QName _DeleteContact_QNAME = new QName("http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", "deleteContact");
    private final static QName _CreatePayor_QNAME = new QName("http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", "createPayor");
    private final static QName _FindAnnuityHolderResponse_QNAME = new QName("http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", "findAnnuityHolderResponse");
    private final static QName _ServerPersistenceModuleException_QNAME = new QName("http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", "ServerPersistenceModuleException");
    private final static QName _FindPayorAnnuities_QNAME = new QName("http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", "findPayorAnnuities");
    private final static QName _CreateContactResponse_QNAME = new QName("http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", "createContactResponse");
    private final static QName _FindContactById_QNAME = new QName("http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", "findContactById");
    private final static QName _FindHolderByIdResponse_QNAME = new QName("http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", "findHolderByIdResponse");
    private final static QName _DeletePayoutResponse_QNAME = new QName("http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", "deletePayoutResponse");
    private final static QName _FindPayoutByIdResponse_QNAME = new QName("http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", "findPayoutByIdResponse");
    private final static QName _UpdateContact_QNAME = new QName("http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", "updateContact");
    private final static QName _FindRiderByIdResponse_QNAME = new QName("http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", "findRiderByIdResponse");
    private final static QName _CreateAnnuityHolderResponse_QNAME = new QName("http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", "createAnnuityHolderResponse");
    private final static QName _DeleteRider_QNAME = new QName("http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", "deleteRider");
    private final static QName _FindAnnuityHolder_QNAME = new QName("http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", "findAnnuityHolder");
    private final static QName _DeletePayorResponse_QNAME = new QName("http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", "deletePayorResponse");
    private final static QName _ServerBusinessModuleException_QNAME = new QName("http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", "ServerBusinessModuleException");
    private final static QName _CreateContact_QNAME = new QName("http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", "createContact");
    private final static QName _CreateAnnuityResponse_QNAME = new QName("http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", "createAnnuityResponse");
    private final static QName _EntityAlreadyExistsException_QNAME = new QName("http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", "EntityAlreadyExistsException");
    private final static QName _DeleteAnnuityHolderResponse_QNAME = new QName("http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", "deleteAnnuityHolderResponse");
    private final static QName _FindRiderById_QNAME = new QName("http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", "findRiderById");
    private final static QName _FindPayoutById_QNAME = new QName("http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", "findPayoutById");
    private final static QName _DeletePayout_QNAME = new QName("http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", "deletePayout");
    private final static QName _DeleteAnnuityResponse_QNAME = new QName("http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", "deleteAnnuityResponse");
    private final static QName _UpdatePayoutResponse_QNAME = new QName("http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", "updatePayoutResponse");
    private final static QName _FindHolderById_QNAME = new QName("http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", "findHolderById");
    private final static QName _FindHolderAnnuitiesResponse_QNAME = new QName("http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", "findHolderAnnuitiesResponse");
    private final static QName _CreateAnnuityHolder_QNAME = new QName("http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", "createAnnuityHolder");
    private final static QName _CreatePayoutResponse_QNAME = new QName("http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", "createPayoutResponse");
    private final static QName _UpdatePayorResponse_QNAME = new QName("http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", "updatePayorResponse");
    private final static QName _DeletePayor_QNAME = new QName("http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", "deletePayor");
    private final static QName _FindPayorByIdResponse_QNAME = new QName("http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", "findPayorByIdResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FindHolderByIdResponse }
     * 
     */
    public FindHolderByIdResponse createFindHolderByIdResponse() {
        return new FindHolderByIdResponse();
    }

    /**
     * Create an instance of {@link CreateAnnuityHolderResponse }
     * 
     */
    public CreateAnnuityHolderResponse createCreateAnnuityHolderResponse() {
        return new CreateAnnuityHolderResponse();
    }

    /**
     * Create an instance of {@link DeleteContact }
     * 
     */
    public DeleteContact createDeleteContact() {
        return new DeleteContact();
    }

    /**
     * Create an instance of {@link DeleteRiderResponse }
     * 
     */
    public DeleteRiderResponse createDeleteRiderResponse() {
        return new DeleteRiderResponse();
    }

    /**
     * Create an instance of {@link UpdatePayorResponse }
     * 
     */
    public UpdatePayorResponse createUpdatePayorResponse() {
        return new UpdatePayorResponse();
    }

    /**
     * Create an instance of {@link DeleteAnnuityResponse }
     * 
     */
    public DeleteAnnuityResponse createDeleteAnnuityResponse() {
        return new DeleteAnnuityResponse();
    }

    /**
     * Create an instance of {@link FindHolderById }
     * 
     */
    public FindHolderById createFindHolderById() {
        return new FindHolderById();
    }

    /**
     * Create an instance of {@link UpdatePayor }
     * 
     */
    public UpdatePayor createUpdatePayor() {
        return new UpdatePayor();
    }

    /**
     * Create an instance of {@link CreatePayorResponse }
     * 
     */
    public CreatePayorResponse createCreatePayorResponse() {
        return new CreatePayorResponse();
    }

    /**
     * Create an instance of {@link InvalidArgumentException }
     * 
     */
    public InvalidArgumentException createInvalidArgumentException() {
        return new InvalidArgumentException();
    }

    /**
     * Create an instance of {@link FindPayorAnnuitiesResponse }
     * 
     */
    public FindPayorAnnuitiesResponse createFindPayorAnnuitiesResponse() {
        return new FindPayorAnnuitiesResponse();
    }

    /**
     * Create an instance of {@link DeleteAnnuityHolder }
     * 
     */
    public DeleteAnnuityHolder createDeleteAnnuityHolder() {
        return new DeleteAnnuityHolder();
    }

    /**
     * Create an instance of {@link CreateContactResponse }
     * 
     */
    public CreateContactResponse createCreateContactResponse() {
        return new CreateContactResponse();
    }

    /**
     * Create an instance of {@link FindRiderByIdResponse }
     * 
     */
    public FindRiderByIdResponse createFindRiderByIdResponse() {
        return new FindRiderByIdResponse();
    }

    /**
     * Create an instance of {@link CreateAnnuityHolder }
     * 
     */
    public CreateAnnuityHolder createCreateAnnuityHolder() {
        return new CreateAnnuityHolder();
    }

    /**
     * Create an instance of {@link DeletePayorResponse }
     * 
     */
    public DeletePayorResponse createDeletePayorResponse() {
        return new DeletePayorResponse();
    }

    /**
     * Create an instance of {@link DeletePayor }
     * 
     */
    public DeletePayor createDeletePayor() {
        return new DeletePayor();
    }

    /**
     * Create an instance of {@link DeletePayoutResponse }
     * 
     */
    public DeletePayoutResponse createDeletePayoutResponse() {
        return new DeletePayoutResponse();
    }

    /**
     * Create an instance of {@link FindAnnuityHolderResponse }
     * 
     */
    public FindAnnuityHolderResponse createFindAnnuityHolderResponse() {
        return new FindAnnuityHolderResponse();
    }

    /**
     * Create an instance of {@link UpdateAnnuity }
     * 
     */
    public UpdateAnnuity createUpdateAnnuity() {
        return new UpdateAnnuity();
    }

    /**
     * Create an instance of {@link FindRiderById }
     * 
     */
    public FindRiderById createFindRiderById() {
        return new FindRiderById();
    }

    /**
     * Create an instance of {@link DeletePayout }
     * 
     */
    public DeletePayout createDeletePayout() {
        return new DeletePayout();
    }

    /**
     * Create an instance of {@link FindAnnuityByIdResponse }
     * 
     */
    public FindAnnuityByIdResponse createFindAnnuityByIdResponse() {
        return new FindAnnuityByIdResponse();
    }

    /**
     * Create an instance of {@link CreatePayout }
     * 
     */
    public CreatePayout createCreatePayout() {
        return new CreatePayout();
    }

    /**
     * Create an instance of {@link UpdateContactResponse }
     * 
     */
    public UpdateContactResponse createUpdateContactResponse() {
        return new UpdateContactResponse();
    }

    /**
     * Create an instance of {@link CreatePayoutResponse }
     * 
     */
    public CreatePayoutResponse createCreatePayoutResponse() {
        return new CreatePayoutResponse();
    }

    /**
     * Create an instance of {@link FindAnnuityHolder }
     * 
     */
    public FindAnnuityHolder createFindAnnuityHolder() {
        return new FindAnnuityHolder();
    }

    /**
     * Create an instance of {@link EntityAlreadyExistsException }
     * 
     */
    public EntityAlreadyExistsException createEntityAlreadyExistsException() {
        return new EntityAlreadyExistsException();
    }

    /**
     * Create an instance of {@link UpdatePayout }
     * 
     */
    public UpdatePayout createUpdatePayout() {
        return new UpdatePayout();
    }

    /**
     * Create an instance of {@link EntityNotFoundException }
     * 
     */
    public EntityNotFoundException createEntityNotFoundException() {
        return new EntityNotFoundException();
    }

    /**
     * Create an instance of {@link FindContactById }
     * 
     */
    public FindContactById createFindContactById() {
        return new FindContactById();
    }

    /**
     * Create an instance of {@link UpdateAnnuityResponse }
     * 
     */
    public UpdateAnnuityResponse createUpdateAnnuityResponse() {
        return new UpdateAnnuityResponse();
    }

    /**
     * Create an instance of {@link UpdateAnnuityHolder }
     * 
     */
    public UpdateAnnuityHolder createUpdateAnnuityHolder() {
        return new UpdateAnnuityHolder();
    }

    /**
     * Create an instance of {@link UpdateContact }
     * 
     */
    public UpdateContact createUpdateContact() {
        return new UpdateContact();
    }

    /**
     * Create an instance of {@link CreateContact }
     * 
     */
    public CreateContact createCreateContact() {
        return new CreateContact();
    }

    /**
     * Create an instance of {@link DeleteAnnuityHolderResponse }
     * 
     */
    public DeleteAnnuityHolderResponse createDeleteAnnuityHolderResponse() {
        return new DeleteAnnuityHolderResponse();
    }

    /**
     * Create an instance of {@link FindPayorAnnuities }
     * 
     */
    public FindPayorAnnuities createFindPayorAnnuities() {
        return new FindPayorAnnuities();
    }

    /**
     * Create an instance of {@link CreatePayor }
     * 
     */
    public CreatePayor createCreatePayor() {
        return new CreatePayor();
    }

    /**
     * Create an instance of {@link UpdatePayoutResponse }
     * 
     */
    public UpdatePayoutResponse createUpdatePayoutResponse() {
        return new UpdatePayoutResponse();
    }

    /**
     * Create an instance of {@link FindPayoutById }
     * 
     */
    public FindPayoutById createFindPayoutById() {
        return new FindPayoutById();
    }

    /**
     * Create an instance of {@link DeleteRider }
     * 
     */
    public DeleteRider createDeleteRider() {
        return new DeleteRider();
    }

    /**
     * Create an instance of {@link DeleteAnnuity }
     * 
     */
    public DeleteAnnuity createDeleteAnnuity() {
        return new DeleteAnnuity();
    }

    /**
     * Create an instance of {@link FindAnnuityById }
     * 
     */
    public FindAnnuityById createFindAnnuityById() {
        return new FindAnnuityById();
    }

    /**
     * Create an instance of {@link FindPayorById }
     * 
     */
    public FindPayorById createFindPayorById() {
        return new FindPayorById();
    }

    /**
     * Create an instance of {@link DeleteContactResponse }
     * 
     */
    public DeleteContactResponse createDeleteContactResponse() {
        return new DeleteContactResponse();
    }

    /**
     * Create an instance of {@link CreateAnnuity }
     * 
     */
    public CreateAnnuity createCreateAnnuity() {
        return new CreateAnnuity();
    }

    /**
     * Create an instance of {@link FindHolderAnnuitiesResponse }
     * 
     */
    public FindHolderAnnuitiesResponse createFindHolderAnnuitiesResponse() {
        return new FindHolderAnnuitiesResponse();
    }

    /**
     * Create an instance of {@link FindPayoutByIdResponse }
     * 
     */
    public FindPayoutByIdResponse createFindPayoutByIdResponse() {
        return new FindPayoutByIdResponse();
    }

    /**
     * Create an instance of {@link UpdateAnnuityHolderResponse }
     * 
     */
    public UpdateAnnuityHolderResponse createUpdateAnnuityHolderResponse() {
        return new UpdateAnnuityHolderResponse();
    }

    /**
     * Create an instance of {@link ServerBusinessModuleException }
     * 
     */
    public ServerBusinessModuleException createServerBusinessModuleException() {
        return new ServerBusinessModuleException();
    }

    /**
     * Create an instance of {@link CreateAnnuityResponse }
     * 
     */
    public CreateAnnuityResponse createCreateAnnuityResponse() {
        return new CreateAnnuityResponse();
    }

    /**
     * Create an instance of {@link FindContactByIdResponse }
     * 
     */
    public FindContactByIdResponse createFindContactByIdResponse() {
        return new FindContactByIdResponse();
    }

    /**
     * Create an instance of {@link FindPayorByIdResponse }
     * 
     */
    public FindPayorByIdResponse createFindPayorByIdResponse() {
        return new FindPayorByIdResponse();
    }

    /**
     * Create an instance of {@link FindHolderAnnuities }
     * 
     */
    public FindHolderAnnuities createFindHolderAnnuities() {
        return new FindHolderAnnuities();
    }

    /**
     * Create an instance of {@link ServerPersistenceModuleException }
     * 
     */
    public ServerPersistenceModuleException createServerPersistenceModuleException() {
        return new ServerPersistenceModuleException();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteAnnuityHolder }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", name = "deleteAnnuityHolder")
    public JAXBElement<DeleteAnnuityHolder> createDeleteAnnuityHolder(DeleteAnnuityHolder value) {
        return new JAXBElement<DeleteAnnuityHolder>(_DeleteAnnuityHolder_QNAME, DeleteAnnuityHolder.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateAnnuity }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", name = "createAnnuity")
    public JAXBElement<CreateAnnuity> createCreateAnnuity(CreateAnnuity value) {
        return new JAXBElement<CreateAnnuity>(_CreateAnnuity_QNAME, CreateAnnuity.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateAnnuityHolderResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", name = "updateAnnuityHolderResponse")
    public JAXBElement<UpdateAnnuityHolderResponse> createUpdateAnnuityHolderResponse(UpdateAnnuityHolderResponse value) {
        return new JAXBElement<UpdateAnnuityHolderResponse>(_UpdateAnnuityHolderResponse_QNAME, UpdateAnnuityHolderResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EntityNotFoundException }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", name = "EntityNotFoundException")
    public JAXBElement<EntityNotFoundException> createEntityNotFoundException(EntityNotFoundException value) {
        return new JAXBElement<EntityNotFoundException>(_EntityNotFoundException_QNAME, EntityNotFoundException.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindHolderAnnuities }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", name = "findHolderAnnuities")
    public JAXBElement<FindHolderAnnuities> createFindHolderAnnuities(FindHolderAnnuities value) {
        return new JAXBElement<FindHolderAnnuities>(_FindHolderAnnuities_QNAME, FindHolderAnnuities.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateAnnuityResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", name = "updateAnnuityResponse")
    public JAXBElement<UpdateAnnuityResponse> createUpdateAnnuityResponse(UpdateAnnuityResponse value) {
        return new JAXBElement<UpdateAnnuityResponse>(_UpdateAnnuityResponse_QNAME, UpdateAnnuityResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreatePayorResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", name = "createPayorResponse")
    public JAXBElement<CreatePayorResponse> createCreatePayorResponse(CreatePayorResponse value) {
        return new JAXBElement<CreatePayorResponse>(_CreatePayorResponse_QNAME, CreatePayorResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteContactResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", name = "deleteContactResponse")
    public JAXBElement<DeleteContactResponse> createDeleteContactResponse(DeleteContactResponse value) {
        return new JAXBElement<DeleteContactResponse>(_DeleteContactResponse_QNAME, DeleteContactResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindAnnuityByIdResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", name = "findAnnuityByIdResponse")
    public JAXBElement<FindAnnuityByIdResponse> createFindAnnuityByIdResponse(FindAnnuityByIdResponse value) {
        return new JAXBElement<FindAnnuityByIdResponse>(_FindAnnuityByIdResponse_QNAME, FindAnnuityByIdResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdatePayout }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", name = "updatePayout")
    public JAXBElement<UpdatePayout> createUpdatePayout(UpdatePayout value) {
        return new JAXBElement<UpdatePayout>(_UpdatePayout_QNAME, UpdatePayout.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteAnnuity }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", name = "deleteAnnuity")
    public JAXBElement<DeleteAnnuity> createDeleteAnnuity(DeleteAnnuity value) {
        return new JAXBElement<DeleteAnnuity>(_DeleteAnnuity_QNAME, DeleteAnnuity.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdatePayor }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", name = "updatePayor")
    public JAXBElement<UpdatePayor> createUpdatePayor(UpdatePayor value) {
        return new JAXBElement<UpdatePayor>(_UpdatePayor_QNAME, UpdatePayor.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreatePayout }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", name = "createPayout")
    public JAXBElement<CreatePayout> createCreatePayout(CreatePayout value) {
        return new JAXBElement<CreatePayout>(_CreatePayout_QNAME, CreatePayout.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindPayorAnnuitiesResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", name = "findPayorAnnuitiesResponse")
    public JAXBElement<FindPayorAnnuitiesResponse> createFindPayorAnnuitiesResponse(FindPayorAnnuitiesResponse value) {
        return new JAXBElement<FindPayorAnnuitiesResponse>(_FindPayorAnnuitiesResponse_QNAME, FindPayorAnnuitiesResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindPayorById }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", name = "findPayorById")
    public JAXBElement<FindPayorById> createFindPayorById(FindPayorById value) {
        return new JAXBElement<FindPayorById>(_FindPayorById_QNAME, FindPayorById.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InvalidArgumentException }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", name = "InvalidArgumentException")
    public JAXBElement<InvalidArgumentException> createInvalidArgumentException(InvalidArgumentException value) {
        return new JAXBElement<InvalidArgumentException>(_InvalidArgumentException_QNAME, InvalidArgumentException.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindContactByIdResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", name = "findContactByIdResponse")
    public JAXBElement<FindContactByIdResponse> createFindContactByIdResponse(FindContactByIdResponse value) {
        return new JAXBElement<FindContactByIdResponse>(_FindContactByIdResponse_QNAME, FindContactByIdResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateContactResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", name = "updateContactResponse")
    public JAXBElement<UpdateContactResponse> createUpdateContactResponse(UpdateContactResponse value) {
        return new JAXBElement<UpdateContactResponse>(_UpdateContactResponse_QNAME, UpdateContactResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateAnnuityHolder }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", name = "updateAnnuityHolder")
    public JAXBElement<UpdateAnnuityHolder> createUpdateAnnuityHolder(UpdateAnnuityHolder value) {
        return new JAXBElement<UpdateAnnuityHolder>(_UpdateAnnuityHolder_QNAME, UpdateAnnuityHolder.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindAnnuityById }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", name = "findAnnuityById")
    public JAXBElement<FindAnnuityById> createFindAnnuityById(FindAnnuityById value) {
        return new JAXBElement<FindAnnuityById>(_FindAnnuityById_QNAME, FindAnnuityById.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateAnnuity }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", name = "updateAnnuity")
    public JAXBElement<UpdateAnnuity> createUpdateAnnuity(UpdateAnnuity value) {
        return new JAXBElement<UpdateAnnuity>(_UpdateAnnuity_QNAME, UpdateAnnuity.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteRiderResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", name = "deleteRiderResponse")
    public JAXBElement<DeleteRiderResponse> createDeleteRiderResponse(DeleteRiderResponse value) {
        return new JAXBElement<DeleteRiderResponse>(_DeleteRiderResponse_QNAME, DeleteRiderResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteContact }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", name = "deleteContact")
    public JAXBElement<DeleteContact> createDeleteContact(DeleteContact value) {
        return new JAXBElement<DeleteContact>(_DeleteContact_QNAME, DeleteContact.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreatePayor }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", name = "createPayor")
    public JAXBElement<CreatePayor> createCreatePayor(CreatePayor value) {
        return new JAXBElement<CreatePayor>(_CreatePayor_QNAME, CreatePayor.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindAnnuityHolderResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", name = "findAnnuityHolderResponse")
    public JAXBElement<FindAnnuityHolderResponse> createFindAnnuityHolderResponse(FindAnnuityHolderResponse value) {
        return new JAXBElement<FindAnnuityHolderResponse>(_FindAnnuityHolderResponse_QNAME, FindAnnuityHolderResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServerPersistenceModuleException }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", name = "ServerPersistenceModuleException")
    public JAXBElement<ServerPersistenceModuleException> createServerPersistenceModuleException(ServerPersistenceModuleException value) {
        return new JAXBElement<ServerPersistenceModuleException>(_ServerPersistenceModuleException_QNAME, ServerPersistenceModuleException.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindPayorAnnuities }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", name = "findPayorAnnuities")
    public JAXBElement<FindPayorAnnuities> createFindPayorAnnuities(FindPayorAnnuities value) {
        return new JAXBElement<FindPayorAnnuities>(_FindPayorAnnuities_QNAME, FindPayorAnnuities.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateContactResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", name = "createContactResponse")
    public JAXBElement<CreateContactResponse> createCreateContactResponse(CreateContactResponse value) {
        return new JAXBElement<CreateContactResponse>(_CreateContactResponse_QNAME, CreateContactResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindContactById }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", name = "findContactById")
    public JAXBElement<FindContactById> createFindContactById(FindContactById value) {
        return new JAXBElement<FindContactById>(_FindContactById_QNAME, FindContactById.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindHolderByIdResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", name = "findHolderByIdResponse")
    public JAXBElement<FindHolderByIdResponse> createFindHolderByIdResponse(FindHolderByIdResponse value) {
        return new JAXBElement<FindHolderByIdResponse>(_FindHolderByIdResponse_QNAME, FindHolderByIdResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeletePayoutResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", name = "deletePayoutResponse")
    public JAXBElement<DeletePayoutResponse> createDeletePayoutResponse(DeletePayoutResponse value) {
        return new JAXBElement<DeletePayoutResponse>(_DeletePayoutResponse_QNAME, DeletePayoutResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindPayoutByIdResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", name = "findPayoutByIdResponse")
    public JAXBElement<FindPayoutByIdResponse> createFindPayoutByIdResponse(FindPayoutByIdResponse value) {
        return new JAXBElement<FindPayoutByIdResponse>(_FindPayoutByIdResponse_QNAME, FindPayoutByIdResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateContact }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", name = "updateContact")
    public JAXBElement<UpdateContact> createUpdateContact(UpdateContact value) {
        return new JAXBElement<UpdateContact>(_UpdateContact_QNAME, UpdateContact.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindRiderByIdResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", name = "findRiderByIdResponse")
    public JAXBElement<FindRiderByIdResponse> createFindRiderByIdResponse(FindRiderByIdResponse value) {
        return new JAXBElement<FindRiderByIdResponse>(_FindRiderByIdResponse_QNAME, FindRiderByIdResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateAnnuityHolderResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", name = "createAnnuityHolderResponse")
    public JAXBElement<CreateAnnuityHolderResponse> createCreateAnnuityHolderResponse(CreateAnnuityHolderResponse value) {
        return new JAXBElement<CreateAnnuityHolderResponse>(_CreateAnnuityHolderResponse_QNAME, CreateAnnuityHolderResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteRider }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", name = "deleteRider")
    public JAXBElement<DeleteRider> createDeleteRider(DeleteRider value) {
        return new JAXBElement<DeleteRider>(_DeleteRider_QNAME, DeleteRider.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindAnnuityHolder }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", name = "findAnnuityHolder")
    public JAXBElement<FindAnnuityHolder> createFindAnnuityHolder(FindAnnuityHolder value) {
        return new JAXBElement<FindAnnuityHolder>(_FindAnnuityHolder_QNAME, FindAnnuityHolder.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeletePayorResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", name = "deletePayorResponse")
    public JAXBElement<DeletePayorResponse> createDeletePayorResponse(DeletePayorResponse value) {
        return new JAXBElement<DeletePayorResponse>(_DeletePayorResponse_QNAME, DeletePayorResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServerBusinessModuleException }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", name = "ServerBusinessModuleException")
    public JAXBElement<ServerBusinessModuleException> createServerBusinessModuleException(ServerBusinessModuleException value) {
        return new JAXBElement<ServerBusinessModuleException>(_ServerBusinessModuleException_QNAME, ServerBusinessModuleException.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateContact }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", name = "createContact")
    public JAXBElement<CreateContact> createCreateContact(CreateContact value) {
        return new JAXBElement<CreateContact>(_CreateContact_QNAME, CreateContact.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateAnnuityResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", name = "createAnnuityResponse")
    public JAXBElement<CreateAnnuityResponse> createCreateAnnuityResponse(CreateAnnuityResponse value) {
        return new JAXBElement<CreateAnnuityResponse>(_CreateAnnuityResponse_QNAME, CreateAnnuityResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EntityAlreadyExistsException }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", name = "EntityAlreadyExistsException")
    public JAXBElement<EntityAlreadyExistsException> createEntityAlreadyExistsException(EntityAlreadyExistsException value) {
        return new JAXBElement<EntityAlreadyExistsException>(_EntityAlreadyExistsException_QNAME, EntityAlreadyExistsException.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteAnnuityHolderResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", name = "deleteAnnuityHolderResponse")
    public JAXBElement<DeleteAnnuityHolderResponse> createDeleteAnnuityHolderResponse(DeleteAnnuityHolderResponse value) {
        return new JAXBElement<DeleteAnnuityHolderResponse>(_DeleteAnnuityHolderResponse_QNAME, DeleteAnnuityHolderResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindRiderById }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", name = "findRiderById")
    public JAXBElement<FindRiderById> createFindRiderById(FindRiderById value) {
        return new JAXBElement<FindRiderById>(_FindRiderById_QNAME, FindRiderById.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindPayoutById }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", name = "findPayoutById")
    public JAXBElement<FindPayoutById> createFindPayoutById(FindPayoutById value) {
        return new JAXBElement<FindPayoutById>(_FindPayoutById_QNAME, FindPayoutById.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeletePayout }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", name = "deletePayout")
    public JAXBElement<DeletePayout> createDeletePayout(DeletePayout value) {
        return new JAXBElement<DeletePayout>(_DeletePayout_QNAME, DeletePayout.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteAnnuityResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", name = "deleteAnnuityResponse")
    public JAXBElement<DeleteAnnuityResponse> createDeleteAnnuityResponse(DeleteAnnuityResponse value) {
        return new JAXBElement<DeleteAnnuityResponse>(_DeleteAnnuityResponse_QNAME, DeleteAnnuityResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdatePayoutResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", name = "updatePayoutResponse")
    public JAXBElement<UpdatePayoutResponse> createUpdatePayoutResponse(UpdatePayoutResponse value) {
        return new JAXBElement<UpdatePayoutResponse>(_UpdatePayoutResponse_QNAME, UpdatePayoutResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindHolderById }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", name = "findHolderById")
    public JAXBElement<FindHolderById> createFindHolderById(FindHolderById value) {
        return new JAXBElement<FindHolderById>(_FindHolderById_QNAME, FindHolderById.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindHolderAnnuitiesResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", name = "findHolderAnnuitiesResponse")
    public JAXBElement<FindHolderAnnuitiesResponse> createFindHolderAnnuitiesResponse(FindHolderAnnuitiesResponse value) {
        return new JAXBElement<FindHolderAnnuitiesResponse>(_FindHolderAnnuitiesResponse_QNAME, FindHolderAnnuitiesResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateAnnuityHolder }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", name = "createAnnuityHolder")
    public JAXBElement<CreateAnnuityHolder> createCreateAnnuityHolder(CreateAnnuityHolder value) {
        return new JAXBElement<CreateAnnuityHolder>(_CreateAnnuityHolder_QNAME, CreateAnnuityHolder.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreatePayoutResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", name = "createPayoutResponse")
    public JAXBElement<CreatePayoutResponse> createCreatePayoutResponse(CreatePayoutResponse value) {
        return new JAXBElement<CreatePayoutResponse>(_CreatePayoutResponse_QNAME, CreatePayoutResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdatePayorResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", name = "updatePayorResponse")
    public JAXBElement<UpdatePayorResponse> createUpdatePayorResponse(UpdatePayorResponse value) {
        return new JAXBElement<UpdatePayorResponse>(_UpdatePayorResponse_QNAME, UpdatePayorResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeletePayor }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", name = "deletePayor")
    public JAXBElement<DeletePayor> createDeletePayor(DeletePayor value) {
        return new JAXBElement<DeletePayor>(_DeletePayor_QNAME, DeletePayor.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindPayorByIdResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/", name = "findPayorByIdResponse")
    public JAXBElement<FindPayorByIdResponse> createFindPayorByIdResponse(FindPayorByIdResponse value) {
        return new JAXBElement<FindPayorByIdResponse>(_FindPayorByIdResponse_QNAME, FindPayorByIdResponse.class, null, value);
    }

}
