//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/")
package com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl;
