//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for riderType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="riderType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="REPLACE"/>
 *     &lt;enumeration value="OVERRIDE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "riderType", namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/")
@XmlEnum
public enum RiderType {

    REPLACE,
    OVERRIDE;

    public String value() {
        return name();
    }

    public static RiderType fromValue(String v) {
        return valueOf(v);
    }

}
