//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl;

import javax.xml.ws.WebFault;

@WebFault(name = "ServerPersistenceModuleException", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/")
public class ServerPersistenceModuleException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ServerPersistenceModuleException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ServerPersistenceModuleException_Exception(String message, ServerPersistenceModuleException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param message
     * @param cause
     */
    public ServerPersistenceModuleException_Exception(String message, ServerPersistenceModuleException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.ibm.wssvt.acme.annuity.common.client.jaxws.ejb3impl.ServerPersistenceModuleException
     */
    public ServerPersistenceModuleException getFaultInfo() {
        return faultInfo;
    }

}
