services: docker

jdk:
- openjdk8

git:
  submodules: false

before_install:
- git config --global url.https://$GITHUB_TOKEN@github.ibm.com/was-svt/sharedApps.insteadOf git@github.ibm.com:was-svt/sharedApps.git
- git submodule update --init --recursive
- docker login $CONT_REGISTRY -u $REG_USER -p $REG_PASSWORD
# - git clone git@github.ibm.com:was-svt/quicksec-jakarta.git

# - sudo apt-get -y install maven

script:
#- cd quicksec-jakarta/
- mvn clean package
- docker build -t acme-ee --build-arg REG_USER=$REG_USER --build-arg REG_PASSWORD=$REG_PASSWORD .
- tag=`git log --pretty=format:"%h" -1`
- docker tag acme-ee $CONT_REGISTRY/acme/acme-ee7:$tag
- docker tag acme-ee $CONT_REGISTRY/acme/acme-ee7:jdk8
- docker tag acme-ee $CONT_REGISTRY/acme/acme-ee7:latest
- docker push  $CONT_REGISTRY/acme/acme-ee7:$tag
- docker push  $CONT_REGISTRY/acme/acme-ee7:latest
- docker push  $CONT_REGISTRY/acme/acme-ee7:jdk8
