//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package com.ibm.wssvt.acme.annuity.common.bean.jaxbjpa;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ListOfObject", namespace = "http://bean.common.annuity.acme.wssvt.ibm.com/jaxbjpa/")
public class ListOfObjects {

    @XmlElement
    private ArrayList<Object> objects;

    public List<Object> getObjects() {
    	if (objects == null){
    		this.objects = new ArrayList<Object>();
    	}
        return this.objects;
    }

}
