//
// Generated By:JAX-WS RI IBM 2.0_03-08/14/2007 03:08 PM(foreman)-fcs (JAXB RI IBM 2.0.5-06/12/2007 09:21 PM(Raja)-fcs)
//


package com.ibm.wssvt.acme.annuity.common.bean.jaxbjpa;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ibm.wssvt.acme.annuity.common.bean.jaxbjpa package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AnnuityHolder_QNAME = new QName("http://bean.common.annuity.acme.wssvt.ibm.com/jaxbjpa/", "annuityHolder");
    private final static QName _Person_QNAME = new QName("http://bean.common.annuity.acme.wssvt.ibm.com/jaxbjpa/", "person");
    private final static QName _FixedAnnuity_QNAME = new QName("http://bean.common.annuity.acme.wssvt.ibm.com/jaxbjpa/", "fixedAnnuity");
    private final static QName _Address_QNAME = new QName("http://bean.common.annuity.acme.wssvt.ibm.com/jaxbjpa/", "address");
    private final static QName _EquityAnnuity_QNAME = new QName("http://bean.common.annuity.acme.wssvt.ibm.com/jaxbjpa/", "equityAnnuity");
    private final static QName _Annuity_QNAME = new QName("http://bean.common.annuity.acme.wssvt.ibm.com/jaxbjpa/", "annuity");
    private final static QName _Rider_QNAME = new QName("http://bean.common.annuity.acme.wssvt.ibm.com/jaxbjpa/", "rider");
    private final static QName _PayoutValueObject_QNAME = new QName("http://bean.common.annuity.acme.wssvt.ibm.com/jaxbjpa/", "payoutValueObject");
    private final static QName _Payor_QNAME = new QName("http://bean.common.annuity.acme.wssvt.ibm.com/jaxbjpa/", "payor");
    private final static QName _Contact_QNAME = new QName("http://bean.common.annuity.acme.wssvt.ibm.com/jaxbjpa/", "contact");
    private final static QName _StringParameterizable_QNAME = new QName("http://bean.common.annuity.acme.wssvt.ibm.com/jaxbjpa/", "stringParameterizable");
    private final static QName _Payout_QNAME = new QName("http://bean.common.annuity.acme.wssvt.ibm.com/jaxbjpa/", "payout");
    private final static QName _AnnuityPersistebleObject_QNAME = new QName("http://bean.common.annuity.acme.wssvt.ibm.com/jaxbjpa/", "annuityPersistebleObject");
    private final static QName _AnnuityValueObject_QNAME = new QName("http://bean.common.annuity.acme.wssvt.ibm.com/jaxbjpa/", "annuityValueObject");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ibm.wssvt.acme.annuity.common.bean.jaxbjpa
     * 
     */
    public ObjectFactory() {
    }

   
    /**
     * Create an instance of {@link Payor }
     * 
     */
    public Payor createPayor() {
        return new Payor();
    }

    /**
     * Create an instance of {@link Rider }
     * 
     */
    public Rider createRider() {
        return new Rider();
    }

    /**
     * Create an instance of {@link AnnuityValueObject }
     * 
     */
    public AnnuityValueObject createAnnuityValueObject() {
        return new AnnuityValueObject();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link StringParameterizable }
     * 
     */
    public StringParameterizable createStringParameterizable() {
        return new StringParameterizable();
    }

    /**
     * Create an instance of {@link AnnuityHolder }
     * 
     */
    public AnnuityHolder createAnnuityHolder() {
        return new AnnuityHolder();
    }

    /**
     * Create an instance of {@link Contact }
     * 
     */
    public Contact createContact() {
        return new Contact();
    }

    /**
     * Create an instance of {@link EquityAnnuity }
     * 
     */
    public EquityAnnuity createEquityAnnuity() {
        return new EquityAnnuity();
    }

    /**
     * Create an instance of {@link FixedAnnuity }
     * 
     */
    public FixedAnnuity createFixedAnnuity() {
        return new FixedAnnuity();
    }

    /**
     * Create an instance of {@link Payout }
     * 
     */
    public Payout createPayout() {
        return new Payout();
    }

   
    /**
     * Create an instance of {@link AnnuityPersistebleObject }
     * 
     */
    public AnnuityPersistebleObject createAnnuityPersistebleObject() {
        return new AnnuityPersistebleObject();
    }

    /**
     * Create an instance of {@link Person }
     * 
     */
    public Person createPerson() {
        return new Person();
    }

    /**
     * Create an instance of {@link Annuity }
     * 
     */
    public Annuity createAnnuity() {
        return new Annuity();
    }

    /**
     * Create an instance of {@link PayoutValueObject }
     * 
     */
    public PayoutValueObject createPayoutValueObject() {
        return new PayoutValueObject();
    }

    public AnnuityJAXRSReturn createAnnuityJAXRSReturn(){
    	return new AnnuityJAXRSReturn ();
    }
    
    public ListOfObjects createListOfObjects(){
    	return new ListOfObjects ();
    }
    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnnuityHolder }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bean.common.annuity.acme.wssvt.ibm.com/jaxbjpa/", name = "annuityHolder")
    public JAXBElement<AnnuityHolder> createAnnuityHolder(AnnuityHolder value) {
        return new JAXBElement<AnnuityHolder>(_AnnuityHolder_QNAME, AnnuityHolder.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Person }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bean.common.annuity.acme.wssvt.ibm.com/jaxbjpa/", name = "person")
    public JAXBElement<Person> createPerson(Person value) {
        return new JAXBElement<Person>(_Person_QNAME, Person.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FixedAnnuity }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bean.common.annuity.acme.wssvt.ibm.com/jaxbjpa/", name = "fixedAnnuity")
    public JAXBElement<FixedAnnuity> createFixedAnnuity(FixedAnnuity value) {
        return new JAXBElement<FixedAnnuity>(_FixedAnnuity_QNAME, FixedAnnuity.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Address }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bean.common.annuity.acme.wssvt.ibm.com/jaxbjpa/", name = "address")
    public JAXBElement<Address> createAddress(Address value) {
        return new JAXBElement<Address>(_Address_QNAME, Address.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EquityAnnuity }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bean.common.annuity.acme.wssvt.ibm.com/jaxbjpa/", name = "equityAnnuity")
    public JAXBElement<EquityAnnuity> createEquityAnnuity(EquityAnnuity value) {
        return new JAXBElement<EquityAnnuity>(_EquityAnnuity_QNAME, EquityAnnuity.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Annuity }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bean.common.annuity.acme.wssvt.ibm.com/jaxbjpa/", name = "annuity")
    public JAXBElement<Annuity> createAnnuity(Annuity value) {
        return new JAXBElement<Annuity>(_Annuity_QNAME, Annuity.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Rider }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bean.common.annuity.acme.wssvt.ibm.com/jaxbjpa/", name = "rider")
    public JAXBElement<Rider> createRider(Rider value) {
        return new JAXBElement<Rider>(_Rider_QNAME, Rider.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PayoutValueObject }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bean.common.annuity.acme.wssvt.ibm.com/jaxbjpa/", name = "payoutValueObject")
    public JAXBElement<PayoutValueObject> createPayoutValueObject(PayoutValueObject value) {
        return new JAXBElement<PayoutValueObject>(_PayoutValueObject_QNAME, PayoutValueObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Payor }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bean.common.annuity.acme.wssvt.ibm.com/jaxbjpa/", name = "payor")
    public JAXBElement<Payor> createPayor(Payor value) {
        return new JAXBElement<Payor>(_Payor_QNAME, Payor.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Contact }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bean.common.annuity.acme.wssvt.ibm.com/jaxbjpa/", name = "contact")
    public JAXBElement<Contact> createContact(Contact value) {
        return new JAXBElement<Contact>(_Contact_QNAME, Contact.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StringParameterizable }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bean.common.annuity.acme.wssvt.ibm.com/jaxbjpa/", name = "stringParameterizable")
    public JAXBElement<StringParameterizable> createStringParameterizable(StringParameterizable value) {
        return new JAXBElement<StringParameterizable>(_StringParameterizable_QNAME, StringParameterizable.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Payout }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bean.common.annuity.acme.wssvt.ibm.com/jaxbjpa/", name = "payout")
    public JAXBElement<Payout> createPayout(Payout value) {
        return new JAXBElement<Payout>(_Payout_QNAME, Payout.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnnuityPersistebleObject }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bean.common.annuity.acme.wssvt.ibm.com/jaxbjpa/", name = "annuityPersistebleObject")
    public JAXBElement<AnnuityPersistebleObject> createAnnuityPersistebleObject(AnnuityPersistebleObject value) {
        return new JAXBElement<AnnuityPersistebleObject>(_AnnuityPersistebleObject_QNAME, AnnuityPersistebleObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnnuityValueObject }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bean.common.annuity.acme.wssvt.ibm.com/jaxbjpa/", name = "annuityValueObject")
    public JAXBElement<AnnuityValueObject> createAnnuityValueObject(AnnuityValueObject value) {
        return new JAXBElement<AnnuityValueObject>(_AnnuityValueObject_QNAME, AnnuityValueObject.class, null, value);
    }

}
