//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package com.ibm.wssvt.acme.annuity.business.impl.ejbws.ejb3jaxws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement(name = "findPayorById", namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "findPayorById", namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/")
public class FindPayorById {

    @XmlElement(name = "arg0", namespace = "")
    private com.ibm.wssvt.acme.annuity.common.bean.jaxbjpa.Payor arg0;

    /**
     * 
     * @return
     *     returns Payor
     */
    public com.ibm.wssvt.acme.annuity.common.bean.jaxbjpa.Payor getArg0() {
        return this.arg0;
    }

    /**
     * 
     * @param arg0
     *     the value for the arg0 property
     */
    public void setArg0(com.ibm.wssvt.acme.annuity.common.bean.jaxbjpa.Payor arg0) {
        this.arg0 = arg0;
    }

}
