//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package com.ibm.wssvt.acme.annuity.business.impl.ejbws.ejb3jaxws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement(name = "updatePayoutResponse", namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "updatePayoutResponse", namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/")
public class UpdatePayoutResponse {

    @XmlElement(name = "return", namespace = "")
    private com.ibm.wssvt.acme.annuity.common.bean.jaxbjpa.PayoutValueObject _return;

    /**
     * 
     * @return
     *     returns PayoutValueObject
     */
    public com.ibm.wssvt.acme.annuity.common.bean.jaxbjpa.PayoutValueObject getReturn() {
        return this._return;
    }

    /**
     * 
     * @param _return
     *     the value for the _return property
     */
    public void setReturn(com.ibm.wssvt.acme.annuity.common.bean.jaxbjpa.PayoutValueObject _return) {
        this._return = _return;
    }

}
