apiVersion: apps.openliberty.io/v1beta2
kind: OpenLibertyApplication
metadata:
    name: acme-ee7
    annotations:
      argocd.argoproj.io/sync-wave: "5"
spec:
  #applicationImage: docker-na-public.artifactory.swg-devops.com/hyc-wassvt-team-image-registry-docker-local/acme/acme-ee7:latest
  applicationImage: libr-proxy1.fyre.ibm.com:5003/docker-registry-svt/v2/acme/acme-ee7:latest
  statefulSet: {}
  createKnativeService: false
  expose: true
  serviceability:
    size: 2Gi  
  replicas: 1
  autoscaling:
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
  pullPolicy: Always
  service:
    type: ClusterIP
    port: 9443
  route:
    termination: passthrough
    annotations:
       haproxy.router.openshift.io/timeout: 4m
  resources:
    limits:
      cpu: 1024m
      memory: 2048Mi
    requests:
      cpu: 1024m
      memory: 2048Mi

  probes:
    startup:
      httpGet:
        path: /health/started
        port: 9080
        scheme: HTTP
      initialDelaySeconds: 180
      periodSeconds: 20
      successThreshold: 1
      failureThreshold: 50
    readiness:
      httpGet:
        path: /health/ready
        port: 9080
        scheme: HTTP
      initialDelaySeconds: 360
    liveness:
      httpGet:
        path: /health/live
        port: 9080
        scheme: HTTP
      initialDelaySeconds: 360
  env:
    - name: DBHost
      value: 'acme-db2'
    - name: DBName
      value: ANNUITY
    - name: DBPort
      value: "50000"
    - name: DBUser
      value: db2inst1
    - name: DBPass
      value: db2passwd
    - name: ldapHost
      value: 'svt-openldap'
    - name: ldapPort
      value: "9389"
    - name: ldapSSL
      value: 'false'