apiVersion: liberty.websphere.ibm.com/v1
kind: WebSphereLibertyApplication
metadata:
    name: acme-ee7
    annotations:
      argocd.argoproj.io/sync-wave: "5"
spec:
  license:
    accept: true
  #applicationImage: docker-na-public.artifactory.swg-devops.com/hyc-wassvt-team-image-registry-docker-local/acme/acme-ee7:latest
  applicationImage: libr-proxy1.fyre.ibm.com:5003/docker-registry-svt/v2/acme/acme-ee7:latest
  statefulSet: 
    storage:
      size: 2Gi
      mountPath: "/logs"
  createKnativeService: false
  expose: true
  serviceability:
    size: 2Gi  
  replicas: 1
  autoscaling:
    minReplicas: 1
    maxReplicas: 20
    targetCPUUtilizationPercentage: 80
  pullPolicy: Always
  service:
    type: ClusterIP
    port: 9443
  resources:
    limits:
      cpu: 512m
      memory: 2048Mi
    requests:
      cpu: 512m
      memory: 1024Mi
  route:
    annotations:
       haproxy.router.openshift.io/timeout: 4m
  probes:
    readiness: {}
    liveness: {}
    startup: {}
  env:
    - name: DBHost
      value: 'acme-db2'
    - name: DBName
      value: ANNUITY
    - name: DBPort
      value: "50000"
    - name: DBUser
      value: db2inst1
    - name: DBPass
      value: db2passwd