package com.ibm.wssvt.acme.annuity.common.util;

public enum AnnuityServiceName {
	EJB31, EJB30, EJB2x,
	POJO_JAXWS,	POJO_JAXRPC, 
	EJB30JAXWS_EJB, EJB30JAXWS_JAXWS,
	EJB30JAXRPC_EJB, EJB30JAXRPC_JAXRPC,
	EJB2xJAXRPC_EJB, EJB2xJAXRPC_JAXRPC,
	JAXRS_1, JAXRS_2, SPECIAL_SERVICE;
}
