//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package com.ibm.wssvt.acme.annuity.business.impl.ejbws.ejb3jaxws.jaxws;

import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement(name = "findPayorAnnuitiesResponse", namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "findPayorAnnuitiesResponse", namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/ejb3impl/")
public class FindPayorAnnuitiesResponse {

    @XmlElement(name = "return", namespace = "")
    private List<com.ibm.wssvt.acme.annuity.common.bean.jaxbjpa.AnnuityValueObject> _return;

    /**
     * 
     * @return
     *     returns List<AnnuityValueObject>
     */
    public List<com.ibm.wssvt.acme.annuity.common.bean.jaxbjpa.AnnuityValueObject> getReturn() {
        return this._return;
    }

    /**
     * 
     * @param _return
     *     the value for the _return property
     */
    public void setReturn(List<com.ibm.wssvt.acme.annuity.common.bean.jaxbjpa.AnnuityValueObject> _return) {
        this._return = _return;
    }

}
