package com.ibm.wssvt.acme.annuity.common.util;


public enum AnnuityAction {
	FIND_ANNUITY_BY_ID,
	FIND_HOLDER_BY_ID, FIND_CONTACT_BY_ID,FIND_HOLDER_ANNUITIES,
	FIND_ANNUITY_HOLDER, FIND_PAYOR_ANNUITIES,FIND_PAYOR_BY_ID,
	FIND_PAYOUT_BY_ID, FIND_RIDER_BY_ID,
	CREATE_ANNUITY, UPDATE_ANNUITY, DELETE_ANNUITY,
	CREATE_ANNUITY_HOLDER,UPDATE_ANNUITY_HOLDER, DELETE_ANNUITY_HOLDER,
	CREATE_PAYOR, UPDATE_PAYOR, DELETE_PAYOR,
	CREATE_CONTACT, UPDATE_CONTACT, DELETE_CONTACT,
	CREATE_PAYOUT, UPDATE_PAYOUT, DELETE_PAYOUT,
	DELETE_RIDER,	
}

