//
// Generated By:JAX-WS RI IBM 2.0_03-08/14/2007 03:08 PM(foreman)-fcs (JAXB RI IBM 2.0.5-06/12/2007 09:21 PM(Raja)-fcs)
//


package com.ibm.wssvt.acme.annuity.common.client.jaxws.pojoimpl;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for annuityHolderCategory.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="annuityHolderCategory">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="METAL"/>
 *     &lt;enumeration value="BRONZE"/>
 *     &lt;enumeration value="SILVER"/>
 *     &lt;enumeration value="GOLD"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
@XmlType(name = "annuityHolderCategory", namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/pojoimpl/")
public enum AnnuityHolderCategory {

    METAL,
    BRONZE,
    SILVER,
    GOLD;

    public String value() {
        return name();
    }

    public static AnnuityHolderCategory fromValue(String v) {
        return valueOf(v);
    }

}
