//
// Generated By:JAX-WS RI IBM 2.0_03-08/14/2007 03:08 PM(foreman)-fcs (JAXB RI IBM 2.0.5-06/12/2007 09:21 PM(Raja)-fcs)
//


package com.ibm.wssvt.acme.annuity.common.client.jaxws.pojoimpl;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

@WebServiceClient(name = "AnnuityMgmtSvcPojoJAXWSImpl", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/pojoimpl/", 
		wsdlLocation = "file:/C:/dev/rad75ws/Annuity/webservice/jaxws/WebContent/WEB-INF/wsdl/AnnuityMgmtSvcPojoJAXWSImpl.wsdl")
		//wsdlLocation = "file:/C:/dev/rsa7ws/MyWSWeb/WebContent/WEB-INF/wsdl/AnnuityMgmtSvcPojoJAXWSImpl.wsdl")
public class AnnuityMgmtSvcPojoJAXWSImpl
    extends Service
{

    private final static URL ANNUITYMGMTSVCPOJOJAXWSIMPL_WSDL_LOCATION;

    static {
        URL url = null;
        try {
        	
        	//url = new URL("file:/C:/dev/rsa7ws/MyWSWeb/WebContent/WEB-INF/wsdl/AnnuityMgmtSvcPojoJAXWSImpl.wsdl");
        	url = new URL("file:/C:/dev/rad75ws/Annuity/webservice/jaxws/WebContent/WEB-INF/wsdl/AnnuityMgmtSvcPojoJAXWSImpl.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        ANNUITYMGMTSVCPOJOJAXWSIMPL_WSDL_LOCATION = url;
    }

    public AnnuityMgmtSvcPojoJAXWSImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AnnuityMgmtSvcPojoJAXWSImpl() {
        super(ANNUITYMGMTSVCPOJOJAXWSIMPL_WSDL_LOCATION, new QName("http://jaxws.client.common.annuity.acme.wssvt.ibm.com/pojoimpl/", "AnnuityMgmtSvcPojoJAXWSImpl"));
    }

    /**
     * 
     * @return
     *     returns AnnuityMgmtSvcPojoJAXWS
     */
    @WebEndpoint(name = "AnnuityMgmtSvcPojoJAXWSImplPort")
    public AnnuityMgmtSvcPojoJAXWS getAnnuityMgmtSvcPojoJAXWSImplPort() {
        return (AnnuityMgmtSvcPojoJAXWS)super.getPort(new QName("http://jaxws.client.common.annuity.acme.wssvt.ibm.com/pojoimpl/", "AnnuityMgmtSvcPojoJAXWSImplPort"), AnnuityMgmtSvcPojoJAXWS.class);
    }

}
