//
// Generated By:JAX-WS RI IBM 2.0_03-08/14/2007 03:08 PM(foreman)-fcs (JAXB RI IBM 2.0.5-06/12/2007 09:21 PM(Raja)-fcs)
//


package com.ibm.wssvt.acme.annuity.common.client.jaxws.pojoimpl;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.ibm.wssvt.acme.annuity.common.bean.jaxbjpa.AnnuityValueObject;


/**
 * <p>Java class for findPayorAnnuitiesResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="findPayorAnnuitiesResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="return" type="{http://bean.common.annuity.acme.wssvt.ibm.com/jaxbjpa/}AnnuityValueObject" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "findPayorAnnuitiesResponse", namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/pojoimpl/", propOrder = {
    "_return"
})
public class FindPayorAnnuitiesResponse {

    @XmlElement(name = "return")
    protected List<AnnuityValueObject> _return;

    /**
     * Gets the value of the return property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the return property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReturn().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AnnuityValueObject }
     * 
     * 
     */
    public List<AnnuityValueObject> getReturn() {
        if (_return == null) {
            _return = new ArrayList<AnnuityValueObject>();
        }
        return this._return;
    }

}
