//
// Generated By:JAX-WS RI IBM 2.0_03-08/14/2007 03:08 PM(foreman)-fcs (JAXB RI IBM 2.0.5-06/12/2007 09:21 PM(Raja)-fcs)
//


package com.ibm.wssvt.acme.annuity.common.client.jaxws.pojoimpl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

import com.ibm.wssvt.acme.annuity.common.bean.jaxbjpa.Rider;


/**
 * <p>Java class for findRiderById complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="findRiderById">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="arg0" type="{http://bean.common.annuity.acme.wssvt.ibm.com/jaxbjpa/}Rider" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "findRiderById", namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/pojoimpl/", propOrder = {
    "arg0"
})
public class FindRiderById {

    protected Rider arg0;

    /**
     * Gets the value of the arg0 property.
     * 
     * @return
     *     possible object is
     *     {@link Rider }
     *     
     */
    public Rider getArg0() {
        return arg0;
    }

    /**
     * Sets the value of the arg0 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rider }
     *     
     */
    public void setArg0(Rider value) {
        this.arg0 = value;
    }

}
