//
// Generated By:JAX-WS RI IBM 2.0_03-08/14/2007 03:08 PM(foreman)-fcs (JAXB RI IBM 2.0.5-06/12/2007 09:21 PM(Raja)-fcs)
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/pojoimpl/")
package com.ibm.wssvt.acme.annuity.common.client.jaxws.pojoimpl;
