//
// Generated By:JAX-WS RI IBM 2.0_03-08/14/2007 03:08 PM(foreman)-fcs (JAXB RI IBM 2.0.5-06/12/2007 09:21 PM(Raja)-fcs)
//


package com.ibm.wssvt.acme.annuity.common.client.jaxws.pojoimpl;

import javax.xml.ws.WebFault;

@WebFault(name = "ServerBusinessModuleException", targetNamespace = "http://jaxws.client.common.annuity.acme.wssvt.ibm.com/pojoimpl/")
public class ServerBusinessModuleException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ServerBusinessModuleException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public ServerBusinessModuleException_Exception(String message, ServerBusinessModuleException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param message
     * @param faultInfo
     */
    public ServerBusinessModuleException_Exception(String message, ServerBusinessModuleException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.ibm.wssvt.acme.annuity.common.client.jaxws.pojoimpl.ServerBusinessModuleException
     */
    public ServerBusinessModuleException getFaultInfo() {
        return faultInfo;
    }

}
